import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, MapPin, Quote } from 'lucide-react';
import { businessConfig, occasionData } from './data/config';
import { handlePlannerStart } from './utils/conversionHandlers';
import { Header } from './components/layout/Header';
import { ContactActions, Footer } from './components/layout/Footer';
import { Button, Eyebrow, Link } from './components/ui';
import { Reveal } from './components/motion/Reveal';
import { menuSections, featuredMenuItems, searchMenuSections } from './data/menuData';
import { MenuHero } from './components/menu/MenuHero';
import { MenuFilters } from './components/menu/MenuFilters';
import { MenuCategory } from './components/menu/MenuCategory';
import { MenuSelectionBar } from './components/menu/MenuSelectionBar';
import { PlannerPage } from './components/planner/PlannerPage';
import { AssistantWidget } from './components/assistant/AssistantWidget';
import { useMenuSelection } from './hooks/useMenuSelection';
import './styles.css';

const menuCategories = [['South Indian','https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=85'],['North Indian','https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=900&q=85'],['Biryani','https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=85'],['Tiffins & Snacks','https://images.unsplash.com/photo-1630409351217-bc4fa6422075?auto=format&fit=crop&w=900&q=85']];

function Hero(){return <section className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="hero-lines"><i/><i/><i/></div><div className="hero-content"><div className="hero-animate hero-eyebrow"><Eyebrow light>Hyderabad · Since 2019</Eyebrow></div><h1 aria-label="Feasts worth gathering for"><span className="hero-line">Feasts worth</span><span className="hero-line hero-line--italic"><em>gathering for.</em></span></h1><p className="hero-animate hero-copy">Remarkable catering for weddings, celebrations and the moments that bring everyone to the table.</p><div className="hero-actions hero-animate"><Button href="/plan" onClick={handlePlannerStart}>Plan Your Catering</Button><Link href="/menu" className="text-link text-link--light">Explore Our Menu <ArrowRight size={16}/></Link></div></div><div className="hero-caption hero-animate"><span/>Quality · Quantity · Taste · Timely service</div></section>}
function SinceStory(){return <section className="since-section"><div className="since-number">2019</div><Reveal type="image" className="since-main-image"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1300&q=88" alt="A carefully prepared Indian feast" loading="lazy"/></Reveal><div className="since-copy"><Reveal><Eyebrow>Serving Hyderabad since 2019</Eyebrow><h2>Made with the<br/><em>heart of a host.</em></h2></Reveal><Reveal delay={130}><p>For us, a generous meal means more than a full plate. It means flavours that feel familiar, details that feel effortless, and guests who leave feeling looked after.</p></Reveal><Reveal delay={190}><div className="values"><span>Quality</span><span>Quantity</span><span>Taste</span><span>Timely service</span></div></Reveal></div></section>}
function SplitStory(){return <section className="split-story"><div className="split-photo"><div className="parallax-photo"/><span className="photo-note">Every occasion begins<br/>with a warm welcome.</span></div><div className="split-copy"><Reveal><Eyebrow light>Our approach</Eyebrow><h2>Grand in spirit.<br/><em>Precise in detail.</em></h2><p>From the first menu conversation to the final serving, our team works with one purpose: to let you host with ease.</p></Reveal><Reveal delay={120}><ul><li><b>01</b> Thoughtful menus around your gathering</li><li><b>02</b> Pure Veg and Non-Veg catering</li><li><b>03</b> Service that respects your schedule</li></ul></Reveal></div></section>}
function Occasions(){const [active,setActive]=useState(0);const current=occasionData[active];return <section className="occasions"><Reveal className="occasion-heading-reveal"><div className="occasion-heading"><Eyebrow>For the days that matter</Eyebrow><h2>There’s an art to<br/><em>bringing people together.</em></h2></div></Reveal><div className="occasion-experience"><div className="occasion-list">{occasionData.map((item,index)=><button key={item.name} onMouseEnter={()=>setActive(index)} onFocus={()=>setActive(index)} onClick={()=>setActive(index)} className={index===active?'is-active':''}><i>0{index+1}</i>{item.name}<ArrowUpRight size={17}/></button>)}</div><div className="occasion-visual"><img key={current.image} src={current.image} alt={`${current.name} catering occasion`} loading="lazy"/><div><span>Trishul for</span><h3>{current.name}</h3><p>{current.note}</p></div></div></div></section>}
function MenuPreview(){return <section className="food-preview"><div className="food-intro"><Reveal><Eyebrow light>From our kitchen</Eyebrow><h2>A menu with<br/><em>many moods.</em></h2><p>Beloved classics, celebratory favourites and the kind of variety that keeps the table talking.</p><Button href="/menu" variant="ivory">Explore Full Menu</Button></Reveal></div><div className="food-collage">{menuCategories.map(([name,image],index)=><Reveal type="image" delay={index*90} className={`food-tile food-tile--${index+1}`} key={name}><img src={image} alt={name}/><span>{name}</span></Reveal>)}</div></section>}
function Gallery(){const images=[['gallery-a','https://images.unsplash.com/photo-1567337710282-00832b415979?auto=format&fit=crop&w=1100&q=85'],['gallery-b','https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1100&q=85'],['gallery-c','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1100&q=85'],['gallery-d','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1100&q=85']];return <section className="gallery"><Reveal><div className="gallery-title"><Eyebrow>At the table</Eyebrow><h2>A little glimpse<br/>of <em>the good stuff.</em></h2></div></Reveal><div className="gallery-grid">{images.map(([className,source],index)=><Reveal type="image" delay={index*80} className={className} key={className}><img src={source} alt="Food prepared for a Trishul catering experience"/></Reveal>)}</div><p className="gallery-tag">Food, people, celebration —<br/>all in generous measure.</p></section>}
function Testimonial(){return <section className="testimonial"><Reveal><Quote size={42} strokeWidth={1}/><p>Real stories from our hosts will live here soon.</p><span>Testimonials are being collected from Trishul Caterers clients.</span><div className="quote-progress"><i/></div></Reveal></section>}
function PlannerCTA(){return <section className="planner-cta"><div className="planner-orbit"/><Reveal><Eyebrow>Start with an idea</Eyebrow><h2>Planning an event?</h2><p>Build your first catering plan, explore the possibilities and get a clear starting estimate.</p><Button href="/plan" onClick={handlePlannerStart}>Plan Your Catering</Button></Reveal></section>}
function ServiceArea(){return <section className="service-area"><Reveal><MapPin size={25}/><Eyebrow>Rooted in Hyderabad</Eyebrow><h2>From Kukatpally,<br/><em>to your celebration.</em></h2><p>We cater across Hyderabad and surrounding areas. Tell us where you’re gathering, and we’ll help plan the service around it.</p></Reveal></section>}
function Home(){return <main><Hero/><SinceStory/><SplitStory/><Occasions/><MenuPreview/><Gallery/><Testimonial/><PlannerCTA/><ServiceArea/></main>}
function MenuPage(){
 const [activeType,setActiveType]=useState('all'); const [activeCategory,setActiveCategory]=useState(''); const [query,setQuery]=useState(''); const {selectedIds,setSelectedIds}=useMenuSelection();
 useEffect(() => { document.querySelectorAll('.featured-card img').forEach(image => { image.loading = 'lazy'; }); }, []);
 const categoryOptions=useMemo(() => menuSections.filter(section => activeType==='all'||section.type===activeType),[activeType]);
 const searchResult=useMemo(() => searchMenuSections({type:activeType,category:activeCategory,query}),[activeType,activeCategory,query]);
 const results=searchResult.sections;
 const toggleItem=item=>setSelectedIds(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id]);
 const clearFilters=()=>{setActiveType('all');setActiveCategory('');setQuery('')};
 return <main className="menu-page"><MenuHero/><section className="menu-featured"><div><Eyebrow>Highlights from the kitchen</Eyebrow><h2>Not a fixed menu.<br/><em>A starting point.</em></h2></div><p>Every selection is shaped around your guests and the way you want to host.</p><div className="featured-strip">{featuredMenuItems.map((item,index)=><article key={item.name} className={`featured-card featured-card--${index+1}`}><img src={item.image} alt={item.name} loading="lazy" width="1200" height="900"/><span>{item.category}</span><h3>{item.name}</h3></article>)}</div></section><section className="menu-browser"><div className="menu-browser-intro"><Eyebrow>Browse the collection</Eyebrow><h2>Your table,<br/><em>your way.</em></h2><p>Browse dishes, save the ones you like, then take your shortlist into a catering plan.</p></div><MenuFilters activeType={activeType} setActiveType={type=>{setActiveType(type);setActiveCategory('')}} query={query} setQuery={setQuery} categories={categoryOptions} activeCategory={activeCategory} setActiveCategory={setActiveCategory} hasFilters={activeType!=='all'||activeCategory||query} clearFilters={clearFilters}/><div className="menu-results" aria-live="polite">{searchResult.mode==='cross-type'&&<div className="menu-search-notice" role="status"><strong>No {activeType==='veg'?'Veg':'Non-Veg'} dishes match “{query.trim()}”.</strong><span>Found {activeType==='veg'?'non-vegetarian':'vegetarian'} dishes matching your search.</span></div>}{searchResult.mode==='category-empty'&&<div className="menu-search-notice" role="status"><strong>No dishes in this category match “{query.trim()}”.</strong><span>Search the full menu to see matching dishes outside this category.</span><button onClick={()=>setActiveCategory('')}>Search full menu <ArrowRight size={15}/></button></div>}{results.length?results.map(section=><MenuCategory key={section.id} section={section} items={section.items} selectedIds={selectedIds} onToggle={toggleItem}/>):searchResult.mode!=='category-empty'&&<div className="menu-empty"><span>No dishes found</span><h3>Try another search.</h3><p>Search by a dish, ingredient or category name.</p><Button onClick={clearFilters}>Clear filters</Button></div>}</div></section><section className="menu-conversion"><Eyebrow light>Planning an event?</Eyebrow><h2>Build your catering<br/><em>plan.</em></h2><p>Save the dishes you love, then take the next step with Trishul.</p><Button href="/plan" variant="ivory">Plan Your Catering</Button></section><MenuSelectionBar count={selectedIds.length} onClear={()=>setSelectedIds([])}/></main>}
function App(){const path=window.location.pathname;useEffect(()=>{const metadata={ '/':{title:'Trishul Caterers Hyderabad | Wedding, Corporate & Event Catering',description:'Thoughtful vegetarian and non-vegetarian catering for weddings, corporate events and celebrations across Hyderabad.'},'/menu':{title:'Menu | Trishul Caterers Hyderabad',description:'Explore Trishul Caterers vegetarian and non-vegetarian menu selections for Hyderabad celebrations.'},'/plan':{title:'Plan Your Catering | Trishul Caterers Hyderabad',description:'Build an approximate Trishul catering plan for your event, menu, guests and service details.'}}[path] || null;if(!metadata)return;document.title=metadata.title;document.querySelector('meta[name="description"]')?.setAttribute('content',metadata.description);document.querySelector('meta[property="og:title"]')?.setAttribute('content',metadata.title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',metadata.description);document.querySelector('meta[property="og:url"]')?.setAttribute('content',window.location.href);document.querySelector('meta[name="twitter:title"]')?.setAttribute('content',metadata.title);document.querySelector('meta[name="twitter:description"]')?.setAttribute('content',metadata.description);document.querySelector('link[rel="canonical"]')?.setAttribute('href',window.location.href);},[path]);const Page=path==='/menu'?MenuPage:path==='/plan'?PlannerPage:Home;return <><Header/><Page/><Footer/><ContactActions/><AssistantWidget/></>};createRoot(document.getElementById('root')).render(<App/>);
